# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/doctor_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(50)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkbox_paths_Hbox = QtWidgets.QHBoxLayout()
        self.checkbox_paths_Hbox.setObjectName("checkbox_paths_Hbox")
        self.download_checkbox_Vbox = QtWidgets.QVBoxLayout()
        self.download_checkbox_Vbox.setObjectName("download_checkbox_Vbox")
        self.gtf_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.gtf_checkbox.setObjectName("gtf_checkbox")
        self.download_checkbox_Vbox.addWidget(self.gtf_checkbox)
        self.gtf_chr_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.gtf_chr_checkbox.setObjectName("gtf_chr_checkbox")
        self.download_checkbox_Vbox.addWidget(self.gtf_chr_checkbox)
        self.cdna_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.cdna_checkbox.setObjectName("cdna_checkbox")
        self.download_checkbox_Vbox.addWidget(self.cdna_checkbox)
        self.checkbox_paths_Hbox.addLayout(self.download_checkbox_Vbox)
        self.pathsLayout_Vbox = QtWidgets.QVBoxLayout()
        self.pathsLayout_Vbox.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.pathsLayout_Vbox.setContentsMargins(3, -1, 3, -1)
        self.pathsLayout_Vbox.setSpacing(5)
        self.pathsLayout_Vbox.setObjectName("pathsLayout_Vbox")
        self.genomePath_Hbox = QtWidgets.QHBoxLayout()
        self.genomePath_Hbox.setObjectName("genomePath_Hbox")
        self.genome_label = QtWidgets.QLabel(self.centralwidget)
        self.genome_label.setObjectName("genome_label")
        self.genomePath_Hbox.addWidget(self.genome_label)
        spacerItem = QtWidgets.QSpacerItem(61, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.genomePath_Hbox.addItem(spacerItem)
        self.genome_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.genome_lineedit.setObjectName("genome_lineedit")
        self.genomePath_Hbox.addWidget(self.genome_lineedit)
        self.genomeBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.genomeBrowse_button.setObjectName("genomeBrowse_button")
        self.genomePath_Hbox.addWidget(self.genomeBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.genomePath_Hbox)
        self.outPath_Hbox = QtWidgets.QHBoxLayout()
        self.outPath_Hbox.setObjectName("outPath_Hbox")
        self.out_label = QtWidgets.QLabel(self.centralwidget)
        self.out_label.setObjectName("out_label")
        self.outPath_Hbox.addWidget(self.out_label)
        self.out_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.out_lineedit.setObjectName("out_lineedit")
        self.outPath_Hbox.addWidget(self.out_lineedit)
        self.outBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.outBrowse_button.setObjectName("outBrowse_button")
        self.outPath_Hbox.addWidget(self.outBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.outPath_Hbox)
        self.checkbox_paths_Hbox.addLayout(self.pathsLayout_Vbox)
        self.verticalLayout_3.addLayout(self.checkbox_paths_Hbox)
        self.bottomLayout_Hbox = QtWidgets.QHBoxLayout()
        self.bottomLayout_Hbox.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.bottomLayout_Hbox.setContentsMargins(5, 5, -1, -1)
        self.bottomLayout_Hbox.setSpacing(24)
        self.bottomLayout_Hbox.setObjectName("bottomLayout_Hbox")
        self.consoleOutput_textbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleOutput_textbrowser.sizePolicy().hasHeightForWidth())
        self.consoleOutput_textbrowser.setSizePolicy(sizePolicy)
        self.consoleOutput_textbrowser.setMaximumSize(QtCore.QSize(2160, 1400))
        self.consoleOutput_textbrowser.setObjectName("consoleOutput_textbrowser")
        self.bottomLayout_Hbox.addWidget(self.consoleOutput_textbrowser)
        self.button_Vbox = QtWidgets.QVBoxLayout()
        self.button_Vbox.setSpacing(1)
        self.button_Vbox.setObjectName("button_Vbox")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.button_Vbox.addItem(spacerItem1)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.button_Vbox.addWidget(self.download_button)
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setObjectName("run_button")
        self.button_Vbox.addWidget(self.run_button)
        self.bottomLayout_Hbox.addLayout(self.button_Vbox)
        self.verticalLayout_3.addLayout(self.bottomLayout_Hbox)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 25)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gtf_checkbox.setText(_translate("MainWindow", "GTF"))
        self.gtf_chr_checkbox.setText(_translate("MainWindow", "GTF w/ CHR Annotation"))
        self.cdna_checkbox.setText(_translate("MainWindow", "CDNA"))
        self.genome_label.setText(_translate("MainWindow", "Genome Path"))
        self.genomeBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.out_label.setText(_translate("MainWindow", "Download Output Path"))
        self.outBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.run_button.setText(_translate("MainWindow", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

