# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helper_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainLayout_grid = QtWidgets.QGridLayout()
        self.mainLayout_grid.setContentsMargins(5, 0, 6, -1)
        self.mainLayout_grid.setHorizontalSpacing(14)
        self.mainLayout_grid.setVerticalSpacing(7)
        self.mainLayout_grid.setObjectName("mainLayout_grid")
        self.bottomLayout_Hbox = QtWidgets.QHBoxLayout()
        self.bottomLayout_Hbox.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.bottomLayout_Hbox.setContentsMargins(5, 5, -1, -1)
        self.bottomLayout_Hbox.setSpacing(24)
        self.bottomLayout_Hbox.setObjectName("bottomLayout_Hbox")
        self.consoleOutput_textbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleOutput_textbrowser.sizePolicy().hasHeightForWidth())
        self.consoleOutput_textbrowser.setSizePolicy(sizePolicy)
        self.consoleOutput_textbrowser.setMaximumSize(QtCore.QSize(2160, 1400))
        self.consoleOutput_textbrowser.setObjectName("consoleOutput_textbrowser")
        self.bottomLayout_Hbox.addWidget(self.consoleOutput_textbrowser)
        self.runButton_button = QtWidgets.QPushButton(self.centralwidget)
        self.runButton_button.setObjectName("runButton_button")
        self.bottomLayout_Hbox.addWidget(self.runButton_button)
        self.mainLayout_grid.addLayout(self.bottomLayout_Hbox, 1, 0, 1, 2)
        self.pathsLayout_Vbox = QtWidgets.QVBoxLayout()
        self.pathsLayout_Vbox.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.pathsLayout_Vbox.setContentsMargins(3, -1, 3, -1)
        self.pathsLayout_Vbox.setSpacing(5)
        self.pathsLayout_Vbox.setObjectName("pathsLayout_Vbox")
        self.dataPath_Hbox = QtWidgets.QHBoxLayout()
        self.dataPath_Hbox.setObjectName("dataPath_Hbox")
        self.data_label = QtWidgets.QLabel(self.centralwidget)
        self.data_label.setObjectName("data_label")
        self.dataPath_Hbox.addWidget(self.data_label)
        self.data_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.data_lineedit.setObjectName("data_lineedit")
        self.dataPath_Hbox.addWidget(self.data_lineedit)
        self.dataBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.dataBrowse_button.setObjectName("dataBrowse_button")
        self.dataPath_Hbox.addWidget(self.dataBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.dataPath_Hbox)
        self.gtfPath_Hbox = QtWidgets.QHBoxLayout()
        self.gtfPath_Hbox.setObjectName("gtfPath_Hbox")
        self.gtf_label = QtWidgets.QLabel(self.centralwidget)
        self.gtf_label.setObjectName("gtf_label")
        self.gtfPath_Hbox.addWidget(self.gtf_label)
        self.gtf_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.gtf_lineedit.setObjectName("gtf_lineedit")
        self.gtfPath_Hbox.addWidget(self.gtf_lineedit)
        self.gtfBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.gtfBrowse_button.setObjectName("gtfBrowse_button")
        self.gtfPath_Hbox.addWidget(self.gtfBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.gtfPath_Hbox)
        self.fastaPath_Hbox = QtWidgets.QHBoxLayout()
        self.fastaPath_Hbox.setObjectName("fastaPath_Hbox")
        self.fasta_label = QtWidgets.QLabel(self.centralwidget)
        self.fasta_label.setObjectName("fasta_label")
        self.fastaPath_Hbox.addWidget(self.fasta_label)
        self.fasta_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.fasta_lineedit.setObjectName("fasta_lineedit")
        self.fastaPath_Hbox.addWidget(self.fasta_lineedit)
        self.fastaBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.fastaBrowse_button.setObjectName("fastaBrowse_button")
        self.fastaPath_Hbox.addWidget(self.fastaBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.fastaPath_Hbox)
        self.outPath_Hbox = QtWidgets.QHBoxLayout()
        self.outPath_Hbox.setObjectName("outPath_Hbox")
        self.out_label = QtWidgets.QLabel(self.centralwidget)
        self.out_label.setObjectName("out_label")
        self.outPath_Hbox.addWidget(self.out_label)
        self.out_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.out_lineedit.setObjectName("out_lineedit")
        self.outPath_Hbox.addWidget(self.out_lineedit)
        self.outBrowse_button = QtWidgets.QPushButton(self.centralwidget)
        self.outBrowse_button.setObjectName("outBrowse_button")
        self.outPath_Hbox.addWidget(self.outBrowse_button)
        self.pathsLayout_Vbox.addLayout(self.outPath_Hbox)
        self.mainLayout_grid.addLayout(self.pathsLayout_Vbox, 0, 1, 1, 1)
        self.optionsLayout_Vbox = QtWidgets.QVBoxLayout()
        self.optionsLayout_Vbox.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.optionsLayout_Vbox.setObjectName("optionsLayout_Vbox")
        self.analysisGenome_Hbox = QtWidgets.QHBoxLayout()
        self.analysisGenome_Hbox.setObjectName("analysisGenome_Hbox")
        self.analysis_label = QtWidgets.QLabel(self.centralwidget)
        self.analysis_label.setObjectName("analysis_label")
        self.analysisGenome_Hbox.addWidget(self.analysis_label)
        self.analysis_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.analysis_lineedit.setObjectName("analysis_lineedit")
        self.analysisGenome_Hbox.addWidget(self.analysis_lineedit)
        self.genome_label = QtWidgets.QLabel(self.centralwidget)
        self.genome_label.setObjectName("genome_label")
        self.analysisGenome_Hbox.addWidget(self.genome_label)
        self.genome_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.genome_lineedit.setObjectName("genome_lineedit")
        self.analysisGenome_Hbox.addWidget(self.genome_lineedit)
        self.optionsLayout_Vbox.addLayout(self.analysisGenome_Hbox)
        self.adapterStrand_Hbox = QtWidgets.QHBoxLayout()
        self.adapterStrand_Hbox.setObjectName("adapterStrand_Hbox")
        self.adapter_label = QtWidgets.QLabel(self.centralwidget)
        self.adapter_label.setObjectName("adapter_label")
        self.adapterStrand_Hbox.addWidget(self.adapter_label)
        self.adapter_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.adapter_lineedit.setObjectName("adapter_lineedit")
        self.adapterStrand_Hbox.addWidget(self.adapter_lineedit)
        self.strand_label = QtWidgets.QLabel(self.centralwidget)
        self.strand_label.setObjectName("strand_label")
        self.adapterStrand_Hbox.addWidget(self.strand_label)
        self.strand_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.strand_lineedit.setObjectName("strand_lineedit")
        self.adapterStrand_Hbox.addWidget(self.strand_lineedit)
        self.optionsLayout_Vbox.addLayout(self.adapterStrand_Hbox)
        self.alignerCore_Hbox = QtWidgets.QHBoxLayout()
        self.alignerCore_Hbox.setObjectName("alignerCore_Hbox")
        self.aligner_label = QtWidgets.QLabel(self.centralwidget)
        self.aligner_label.setObjectName("aligner_label")
        self.alignerCore_Hbox.addWidget(self.aligner_label)
        self.aligner_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.aligner_lineedit.setObjectName("aligner_lineedit")
        self.alignerCore_Hbox.addWidget(self.aligner_lineedit)
        self.cores_label = QtWidgets.QLabel(self.centralwidget)
        self.cores_label.setObjectName("cores_label")
        self.alignerCore_Hbox.addWidget(self.cores_label)
        self.cores_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.cores_lineedit.setObjectName("cores_lineedit")
        self.alignerCore_Hbox.addWidget(self.cores_lineedit)
        self.optionsLayout_Vbox.addLayout(self.alignerCore_Hbox)
        self.nameSave_Hbox = QtWidgets.QHBoxLayout()
        self.nameSave_Hbox.setObjectName("nameSave_Hbox")
        self.runName_label = QtWidgets.QLabel(self.centralwidget)
        self.runName_label.setObjectName("runName_label")
        self.nameSave_Hbox.addWidget(self.runName_label)
        self.runName_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.runName_lineedit.setObjectName("runName_lineedit")
        self.nameSave_Hbox.addWidget(self.runName_lineedit)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.nameSave_Hbox.addWidget(self.save_button)
        self.optionsLayout_Vbox.addLayout(self.nameSave_Hbox)
        self.mainLayout_grid.addLayout(self.optionsLayout_Vbox, 0, 0, 1, 1)
        self.mainLayout_grid.setRowStretch(0, 75)
        self.verticalLayout_3.addLayout(self.mainLayout_grid)
        MainWindow.setCentralWidget(self.centralwidget)
        self.MainStatus = QtWidgets.QStatusBar(MainWindow)
        self.MainStatus.setObjectName("MainStatus")
        MainWindow.setStatusBar(self.MainStatus)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "bcbio helper"))
        self.runButton_button.setText(_translate("MainWindow", "Run BCBIO"))
        self.data_label.setText(_translate("MainWindow", "Data"))
        self.dataBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.gtf_label.setText(_translate("MainWindow", "GTF"))
        self.gtfBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.fasta_label.setText(_translate("MainWindow", "FASTA"))
        self.fastaBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.out_label.setText(_translate("MainWindow", "Output Path"))
        self.outBrowse_button.setText(_translate("MainWindow", "Browse"))
        self.analysis_label.setText(_translate("MainWindow", "Analysis"))
        self.genome_label.setText(_translate("MainWindow", "Genome"))
        self.adapter_label.setText(_translate("MainWindow", "Adapter"))
        self.strand_label.setText(_translate("MainWindow", "Strandedness"))
        self.aligner_label.setText(_translate("MainWindow", "Aligner"))
        self.cores_label.setText(_translate("MainWindow", "Cores"))
        self.runName_label.setText(_translate("MainWindow", "Run Name"))
        self.save_button.setText(_translate("MainWindow", "Save Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
